# Generated by Django 4.1 on 2022-08-09 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_registrationdetails_delete_registrationform'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegistrationDetails',
        ),
    ]
