# Generated by Django 4.1 on 2022-08-09 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RegistrationDetails',
            new_name='Admission',
        ),
        migrations.AlterModelOptions(
            name='admission',
            options={'verbose_name': 'Admission', 'verbose_name_plural': 'Admission'},
        ),
        migrations.AlterModelTable(
            name='admission',
            table='web_admission',
        ),
    ]
