# Generated by Django 4.1 on 2022-08-09 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_rename_registrationdetails_admission_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Admission',
            new_name='AdmissionApplication',
        ),
    ]
